"""Add task status and timestamps

Revision ID: 1e0a066643e1
Revises: c2710829e8c6
Create Date: 2026-08-01 19:17:51.208379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic.autogenerate.compare import server_defaults

# revision identifiers, used by Alembic.
revision: str = '1e0a066643e1'
down_revision: Union[str, Sequence[str], None] = 'c2710829e8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
